### PR TITLE
Set up a reproducible way of building sources

### PR DESCRIPTION
**Pull request by tripu**
&hellip;(specifically, minified CSS), via npm module `csso-cli` and a custom script; document this on README instead of in particular source files.

@tanyeah, the minified CSS I get is different from the one committed to the repo (?). Can you make sure it's all right?

### CODE REVIEW

**Comment by tripu** [comment]
@iherman:

Minified CSS is the only CSS there used to be in this repo. [I asked @tanyeah](https://github.com/w3c/publishing/pull/6#pullrequestreview-44318108) to upload the source CSS, along with instructions to build the minified version, so that others can make changes, too. [Her instructions then](https://github.com/w3c/publishing/pull/7/files#diff-d768e32f9670460b31c877809a8f4654R6) pointed to the *tool* she uses, but not to the exact *way* she uses it. (For example: when I used that tool myself, the minified CSS I got was different to the one committed to the repo. Either I was not using the same version of `csso` in the same way, or the minified version in `master` does not correspond to the source CSS in `master` right now. @tanyeah, which one is it?)

Thus this PR. I think there should be an unequivocal way for anyone to build the minified CSS from the source CSS, or else there will be spurious changes or weird diffs, and the two files won't be kept in sync.

I don't care whether this is done via Node.js+npm, a portable shell script, a Python one-liner, or in any other way&nbsp;&mdash;&nbsp;as long as it's easy to set up, and reproducible. So, feel free to commit to this branch with an alternative approach, by all means!

**Comment by iherman** [comment]
@tripu 

Oh I see! I did not realize the summit page used a minified css (I was not involved with that part of the site).

I do agree with your starting position (reproducible files for this type of repo) but my take is different: I do not really see the reason for using a minified css iin the first place. The sizes are as follows: `summit.css`: 7.1K (i.e., 496 lines), `summit.min.css`: 5.1K. I would think that for such sizes the absolute sizes as well as the difference in sizes is not worth the trouble... @tanyeah ?

**Comment by tanyeah** [comment]
@tripu, I think I agree with @iherman about having _just_ the `summit.css` file, it's easier for other contributors to go in and change the CSS they need to in the future, as well. 
The only reason I minified it in the first place is because I was following a page structure that Bill wanted me to emulate for the Summit landing page. 
Having worked on the page for a while, though, I don't think it's particularly important to have the minified version.

**Comment by tripu** [comment]
Okay, then! I'm closing this PR.

@tanyeah, are you then replacing the minified file with the source one?

**Comment by tanyeah** [comment]
Will do, @tripu! Thanks!

**Pull request closed without merging**
