### PR TITLE
Pub summit landing page changes

### PR DESCRIPTION
**Pull request by tanyeah**
1. Content + layout changed according to request by Bill
2. Bootstrap & jQuery files removed, using a CDN instead
3. Fonts + images added for landing page

### CODE REVIEW

**Comment by iherman** [comment]
Found some issues that I discussed with Tanya on IRC (choice of Fonts, and the usage of absolute URL-s for favicons), but I will merge this so that it would be operational, and those aspects can be changed later

**Comment by tripu** [comment]
@tanyeah, where are you planning to use that Source Sans Pro (I see it's not used yet)?

Are you planning to use Noto Sans for the bulk of the page here, too?
w3c/wai-website-design#52

**Comment by koalie** [comment]
+1 to Noto Sans (unless it looks ugly), so that we use consistently our new font of choice.

**Comment by tanyeah** [comment]
Will experiment, and make the change. Thanks all!

**Pull request merged**
