### PR TITLE
Styling for summit landing page

### PR DESCRIPTION
**Pull request by tanyeah**

### CODE REVIEW

**Comment by tripu** [comment]
@tanyeah:

Why not use latest jQuery legacy (2.2.4) and Bootstrap (3.3.7) instead? These versions are a bit old.

Also, feel free to assign PRs to me (or anybody else) for review before merging them, if you want :) (It's not required, but in many other of our repos we have grown used to always having somebody else review our changes; to minimise bugs, suggest improvements, etc.)

**Comment by tanyeah** [comment]
Ouch. Thanks for spotting that, @tripu - will do!
The page was modelled on another page, and we needed a rough draft to have a conversation about this afternoon. It's still in definite need of a clean-up before launch.

Great, that helps. Thank you! :)

**Comment by iherman** [comment]
Actually... I do not know about Bootstrap (I do not know what that is), but I believe it is a better idea to use the jquery as stored on our web site, rather than having a copy on the repo. The main index.html file already does that, using:

```
<script src="https://www.w3.org/scripts/jquery/2.1/jquery.min.js"></script>
```

Ivan

**Comment by tripu** [comment]
@iherman, that's another possibility.

I didn't suggest using the files we host under `w3.org` because I'm not sure we want to use those for other things apart from specs. But I would be okay with that, too.

Come to think of it, even better would be to leverage CDNs out there. Nowadays it seems silly to host your own copy of jQuery or Bootstrap (unless you have special requirements about white-listing resources for publishing formal documentation, and about long-term persistence; like we do with our formal specs)&nbsp;&mdash;&nbsp;most likely users have those cached from somewhere already!

**Comment by tanyeah** [comment]
Seconded. I like the idea of using CDNs. Shall I make the change, if there's no objections?

**Pull request merged**
