### PR TITLE
Logo change

### PR DESCRIPTION
**Pull request by iherman**
@tanyeah, I have 

- put the logos onto the repository for an easier access
- changed the logo references accordingly on the home page as well as the summit page

Cc @koalie @whmccoy

### CODE REVIEW

**Comment by tanyeah** [comment]
@iherman, the `logo.svg` file seems to take the new font we decided on, but I don't see that reflecting onto the home page or the Publishing Summit landing page. 

Is there something I'm missing?

**Comment by iherman** [comment]
The font file has been put alongside the SVG file into the same folder in the repo, and is part of this pull request branch.

You can see the end result in: https://rawgit.com/w3c/publishing/logo-change/index.html

**Comment by tanyeah** [comment]
Still don't see it, @iherman, I'm sorry. This is what it looks like to me on Chrome and Firefox, which is very different from `logo.svg`. 

pub
  
It might be me, though. @koalie, @whmccoy, does the logo on [this page](https://rawgit.com/w3c/publishing/logo-change/index.html) match [this](https://rawgit.com/w3c/publishing/logo-change/logo/logo.svg) for you?

**Comment by iherman** [comment]
Hm. Are you sure you are looking at the right version? What does it say if you look at the source view?

**Comment by koalie** [comment]
> @koalie, @whmccoy, does the logo on this page match this for you?

Yes, it does.

**Comment by tanyeah** [comment]
> Hm. Are you sure you are looking at the right version? What does it say if you look at the source view?

@iherman, yep. It looks that way on https://rawgit.com/w3c/publishing/logo-change/index.html, as well. I even disabled all my extensions, just in case there was a possible conflict (although I don't see why there would be).

Looking at 'Sources' in Chrome's Dev Tools for [the page](https://rawgit.com/w3c/publishing/logo-change/index.html), I see `logo.svg` in the logo folder, and nothing else.   

Sources for the [logo](https://rawgit.com/w3c/publishing/logo-change/logo/logo.svg) shows the svg file and the font file.

Although, after Coralie said it looked okay to her, I checked from two other devices and it looks fine there. /me shrugs

I'm inclined to put this down as a problem with my system, and not the files. Shall I approve and merge? 

Or would you like for us to work on a fix?

**Comment by iherman** [comment]
@tanyeah I would prefer to merge it, and we can see. I am not sure how such links work in a commit at github, and I can also imagine that your browsers' cache setting get in the way (it happens very often to me). We can check then.

**Pull request merged**
